export const HE_TV = [["popular", "פופופלרי"], ["airing_today", "עכשיו באוויר"], ["top_rated", "ביקוש גבוה"], ["on_the_air", "משודר עכשיו"]];
export const HE_MOVIE = [["upcoming", "בקרוב"], ["top_rated", "ביקוש גבוה"], ["popular", "פופופלרי"], ["now_playing", "משודר עכשיו"]];
export const EN_TV = [["popular", "POPULAR"], ["airing_today", "AIR TODAY"], ["top_rated", "TOP RATED"], ["on_the_air", "ON THE AIR"]];
export const EN_MOVIE = [["upcoming", "UPCOMING"], ["top_rated", "TOP RATING"], ["popular", "POPULAR"], ["now_playing", "now_playing"]];


export const HE_TV_GENERS = [[10759, 'אקשן ומדע בדיוני'], [16, 'אנימציה'], [35, 'קומדיה'], [80, 'פשע'], [99, 'דוקומנטרי'], [18, 'דרמה'], [10751, 'משפחה'], [10762, 'ילדים'], [9648, 'תעלומה'], [10763, 'חדשות'], [10764, 'ריאלטי'], [10765, 'פנטזיה'], [10766, 'Soap'], [10767, 'תוכניות טלויזיה'], [10768, 'מלחמה'], [37, 'מערבון']];
export const HE_MOVIE_GENERS = [[28, 'אקשן'], [35, 'קומדיה'], [27, 'אימה'], [80, 'פשע'], [18, 'דרמה'], [878, 'מדע בדיוני'], [12, 'הרפתקאות'], [16, 'אנימציה'], [99, 'דוקומנטרי'], [10751, 'משפחה'], [36, 'היסטוריה'], [14, 'פנטזיה'], [9648, 'תעלומה'], [10749, 'רונטיקה'], [53, 'מותחן'], [10752, 'מלחמה']];
export const EN_TV_GENERS = [[10759, 'Action & Adventure'], [16, 'Animation'], [35, 'Comedy'], [80, 'Crime'], [99, 'Documentary'], [18, 'Drama'], [10751, 'Family'], [10762, 'Kids'], [9648, 'Mystery'], [10763, 'News'], [10764, 'Reality'], [10765, 'Sci-Fi & Fantasy'], [10766, 'Soap'], [10767, 'Talk'], [10768, 'War & Politics'], [37, 'Western']];
export const EN_MOVIE_GENERS = [[28, 'Action'], [35, 'Comedy'], [27, 'Horror'], [80, 'Crime'], [18, 'Drama'], [878, 'Science Fiction'], [12, 'Adventure'], [16, 'Animation'], [99, 'Documentary'], [10751, 'Family'], [36, 'History'], [14, 'Fantasy'], [9648, 'Mystery'], [10749, 'Romance'], [53, 'Thriller'], [10752, 'War']];


export const PAGE_FIND = {
    EN: {
        language: "language",
        likes: "Likes",
        year: "Up a year:",
        title_geners: "Choose generes",
        titlecontainer: {
            a: "Searching",
            b: {
                movie: "movies",
                tv: "tv shows"
            }
        },
        select: "select",
        sort: "Sort",
        button: "Find"


    },
    HE: {
        language: "שפה",
        likes: "אהבו",
        year: "ומעלה",
        title_geners: "בחר ז'אנר",
        titlecontainer: {
            a: "חיפוש",
            b: {
                movie: "סרטים",
                tv: "סדרות"
            }
        },
        select: "בחירה",
        sort: "סנן",
        button: "חפש"

    }
}

export const similarContainer = {
    he: "תכנים דומים",
    us: "similar"
}

export const tabs = {
    he: {
        movie: "סרטים",
        tv: "סדרות",
    },
    us: {
        movie: "Movies",
        tv: "Tv",
    }

}

export const COUNTRIES = [

    ["en", "English"],
    ["fr", "French"],
    ["de", "German"],
    ["es", "Spanish; Castilian"],
    ["ja", "Japanese"],
    ["pt", "Portuguese"],
    ["it", "Italian"],
    ["ru", "Russian"],
    ["zh", "Chinese"],
    ["ko", "Korean"],
    ["nl", "Dutch; Flemish"],
    ["sv", "Swedish"],
    ["hi", "Hindi"],
    ["cs", "Czech"],
    ["tr", "Turkish"],
    ["cn", "Cantonese"],
    ["da", "Danish"],
    ["ar", "Arabic"],
    ["ta", "Tamil"],
    ["el", "Greek"],
    ["pl", "Polish"],
    ["ml", "Malayalam"],
    ["tl", "Tagalog"],
    ["id", "Indonesian"],
    ["hu", "Hungarian"],
    ["fa", "Persian"],
    ["fi", "Finnish"],
    ["xx", "No Language"],
    ["no", "Norwegian"],
    ["te", "Telugu"],
    ["th", "Thai"],
    ["sr", "Serbian"],
    ["he", "Hebrew"],
    ["ro", "Romanian"],
    ["hr", "Croatian"],
    ["bn", "Bengali"],
    ["vi", "Vietnamese"],
    ["ms", "Malay"],
    ["kn", "Kannada"],
    ["sl", "Slovenian"],
    ["sk", "Slovak"],
    ["bg", "Bulgarian"],
    ["uk", "Ukrainian"],
    ["et", "Estonian"],
    ["lv", "Latvian"],
    ["mr", "Marathi"],
    ["sq", "Albanian"],
    ["lt", "Lithuanian"],
    ["ca", "Catalan; Valencian"],
    ["ka", "Georgian"],
    ["pa", "Panjabi; Punjabi"],
    ["ur", "Urdu"],
    ["az", "Azerbaijani"],
    ["bs", "Bosnian"],
    ["is", "Icelandic"],
    ["mk", "Macedonian"],
    ["af", "Afrikaans"],
    ["eu", "Basque"],
    ["nb", "Bokmål, Norwegian; Norwegian Bokmål"],
    ["hy", "Armenian"],
    ["ab", "Abkhazian"],
    ["ku", "Kurdish"],
    ["gl", "Galician"],
    ["si", "Sinhala; Sinhalese"],
    ["as", "Assamese"],
    ["ne", "Nepali"],
    ["gu", "Gujarati"],
    ["kk", "Kazakh"],
    ["my", "Burmese"],
    ["mn", "Mongolian"],
    ["km", "Central Khmer"],
    ["am", "Amharic"],
    ["sh", "Serbo-Croatian"],
    ["bo", "Tibetan"],
    ["zu", "Zulu"],
    ["be", "Belarusian"],
    ["jv", "Javanese"],
    ["ky", "Kirghiz; Kyrgyz"],
    ["sw", "Swahili"],
    ["ga", "Irish"],
    ["uz", "Uzbek"],
    ["lb", "Luxembourgish; Letzeburgesch"],
    ["ps", "Pushto; Pashto"],
    ["la", "Latin"],
    ["wo", "Wolof"],
    ["se", "Northern Sami"],
    ["mt", "Maltese"],
    ["iu", "Inuktitut"],
    ["cy", "Welsh"],
    ["gd", "Gaelic; Scottish Gaelic"],
    ["lo", "Lao"],
    ["tg", "Tajik"],
    ["ht", "Haitian; Haitian Creole"],
    ["qu", "Quechua"],
    ["yi", "Yiddish"],
    ["bm", "Bambara"],
    ["fo", "Faroese"],
    ["or", "Oriya"],
    ["dv", "Divehi; Dhivehi; Maldivian"],
    ["nn", "Norwegian Nynorsk; Nynorsk, Norwegian"],
    ["dz", "Dzongkha"],
    ["mi", "Maori"],
    ["so", "Somali"],
    ["eo", "Esperanto"],
    ["mo", "Moldavian; Moldovan"],
    ["hz", "Herero"],
    ["xh", "Xhosa"],
    ["mg", "Malagasy"],
    ["cr", "Cree"],
    ["ak", "Akan"],
    ["ha", "Hausa"],
    ["ln", "Lingala"],
    ["mh", "Marshallese"],
    ["rw", "Kinyarwanda"],
    ["gn", "Guarani"],
    ["tk", "Turkmen"],
    ["sm", "Samoan"],
    ["sa", "Sanskrit"],
    ["ce", "Chechen"],
    ["ti", "Tigrinya"],
    ["st", "Sotho, Southern"],
    ["ba", "Bashkir"],
    ["yo", "Yoruba"],
    ["ie", "Interlingue; Occidental"],
    ["kl", "Kalaallisut; Greenlandic"],
    ["sn", "Shona"],
    ["ks", "Kashmiri"],
    ["fy", "Western Frisian"],
    ["bi", "Bislama"],
    ["su", "Sundanese"],
    ["ny", "Chichewa; Chewa; Nyanja"],
    ["ay", "Aymara"],
    ["ig", "Igbo"],
    ["oc", "Occitan (post 1500)"],
    ["za", "Zhuang; Chuang"],
    ["an", "Aragonese"],
    ["rm", "Romansh"],
    ["sg", "Sango"],
    ["av", "Avaric"],
    ["ff", "Fulah"],
    ["to", "Tonga (Tonga Islands)"],
    ["co", "Corsican"],
    ["ug", "Uighur; Uyghur"],
    ["aa", "Afar"],
    ["os", "Ossetian; Ossetic"],
    ["ii", "Sichuan Yi; Nuosu"],
    ["tn", "Tswana"],
    ["lg", "Ganda"],
    ["pi", "Pali"],
    ["sd", "Sindhi"],
    ["ss", "Swati"],
    ["ho", "Hiri Motu"],
    ["fj", "Fijian"],
    ["ty", "Tahitian"],
    ["kg", "Kongo"],
    ["tt", "Tatar"],
    ["ik", "Inupiaq"],
    ["gv", "Manx"],
    ["ch", "Chamorro"],
    ["oj", "Ojibwa"],
    ["ts", "Tsonga"],
    ["kw", "Cornish"]
]
export const FLAGS_CDDE = [
    { "name": "Afghanistan", "code": "AF" },
    { "name": "land Islands", "code": "AX" },
    { "name": "Albania", "code": "AL" },
    { "name": "Algeria", "code": "DZ" },
    { "name": "American Samoa", "code": "AS" },
    { "name": "AndorrA", "code": "AD" },
    { "name": "Angola", "code": "AO" },
    { "name": "Anguilla", "code": "AI" },
    { "name": "Antarctica", "code": "AQ" },
    { "name": "Antigua and Barbuda", "code": "AG" },
    { "name": "Argentina", "code": "AR" },
    { "name": "Armenia", "code": "AM" },
    { "name": "Aruba", "code": "AW" },
    { "name": "Australia", "code": "AU" },
    { "name": "Austria", "code": "AT" },
    { "name": "Azerbaijan", "code": "AZ" },
    { "name": "Bahamas", "code": "BS" },
    { "name": "Bahrain", "code": "BH" },
    { "name": "Bangladesh", "code": "BD" },
    { "name": "Barbados", "code": "BB" },
    { "name": "Belarus", "code": "BY" },
    { "name": "Belgium", "code": "BE" },
    { "name": "Belize", "code": "BZ" },
    { "name": "Benin", "code": "BJ" },
    { "name": "Bermuda", "code": "BM" },
    { "name": "Bhutan", "code": "BT" },
    { "name": "Bolivia", "code": "BO" },
    { "name": "Bosnia and Herzegovina", "code": "BA" },
    { "name": "Botswana", "code": "BW" },
    { "name": "Bouvet Island", "code": "BV" },
    { "name": "Brazil", "code": "BR" },
    { "name": "British Indian Ocean Territory", "code": "IO" },
    { "name": "Brunei Darussalam", "code": "BN" },
    { "name": "Bulgaria", "code": "BG" },
    { "name": "Burkina Faso", "code": "BF" },
    { "name": "Burundi", "code": "BI" },
    { "name": "Cambodia", "code": "KH" },
    { "name": "Cameroon", "code": "CM" },
    { "name": "Canada", "code": "CA" },
    { "name": "Cape Verde", "code": "CV" },
    { "name": "Cayman Islands", "code": "KY" },
    { "name": "Central African Republic", "code": "CF" },
    { "name": "Chad", "code": "TD" },
    { "name": "Chile", "code": "CL" },
    { "name": "China", "code": "CN" },
    { "name": "Christmas Island", "code": "CX" },
    { "name": "Cocos (Keeling) Islands", "code": "CC" },
    { "name": "Colombia", "code": "CO" },
    { "name": "Comoros", "code": "KM" },
    { "name": "Congo", "code": "CG" },
    { "name": "Congo, The Democratic Republic of the", "code": "CD" },
    { "name": "Cook Islands", "code": "CK" },
    { "name": "Costa Rica", "code": "CR" },
    { "name": 'Cote D"Ivoire', "code": "CI" },
    { "name": "Croatia", "code": "HR" },
    { "name": "Cuba", "code": "CU" },
    { "name": "Cyprus", "code": "CY" },
    { "name": "Czech Republic", "code": "CZ" },
    { "name": "Denmark", "code": "DK" },
    { "name": "Djibouti", "code": "DJ" },
    { "name": "Dominica", "code": "DM" },
    { "name": "Dominican Republic", "code": "DO" },
    { "name": "Ecuador", "code": "EC" },
    { "name": "Egypt", "code": "EG" },
    { "name": "El Salvador", "code": "SV" },
    { "name": "Equatorial Guinea", "code": "GQ" },
    { "name": "Eritrea", "code": "ER" },
    { "name": "Estonia", "code": "EE" },
    { "name": "Ethiopia", "code": "ET" },
    { "name": "Falkland Islands (Malvinas)", "code": "FK" },
    { "name": "Faroe Islands", "code": "FO" },
    { "name": "Fiji", "code": "FJ" },
    { "name": "Finland", "code": "FI" },
    { "name": "France", "code": "FR" },
    { "name": "French Guiana", "code": "GF" },
    { "name": "French Polynesia", "code": "PF" },
    { "name": "French Southern Territories", "code": "TF" },
    { "name": "Gabon", "code": "GA" },
    { "name": "Gambia", "code": "GM" },
    { "name": "Georgia", "code": "GE" },
    { "name": "Germany", "code": "DE" },
    { "name": "Ghana", "code": "GH" },
    { "name": "Gibraltar", "code": "GI" },
    { "name": "Greece", "code": "GR" },
    { "name": "Greenland", "code": "GL" },
    { "name": "Grenada", "code": "GD" },
    { "name": "Guadeloupe", "code": "GP" },
    { "name": "Guam", "code": "GU" },
    { "name": "Guatemala", "code": "GT" },
    { "name": "Guernsey", "code": "GG" },
    { "name": "Guinea", "code": "GN" },
    { "name": "Guinea-Bissau", "code": "GW" },
    { "name": "Guyana", "code": "GY" },
    { "name": "Haiti", "code": "HT" },
    { "name": "Heard Island and Mcdonald Islands", "code": "HM" },
    { "name": "Holy See (Vatican City State)", "code": "VA" },
    { "name": "Honduras", "code": "HN" },
    { "name": "Hong Kong", "code": "HK" },
    { "name": "Hungary", "code": "HU" },
    { "name": "Iceland", "code": "IS" },
    { "name": "India", "code": "IN" },
    { "name": "Indonesia", "code": "ID" },
    { "name": "Iran, Islamic Republic Of", "code": "IR" },
    { "name": "Iraq", "code": "IQ" },
    { "name": "Ireland", "code": "IE" },
    { "name": "Isle of Man", "code": "IM" },
    { "name": "Israel", "code": "IL" },
    { "name": "Italy", "code": "IT" },
    { "name": "Jamaica", "code": "JM" },
    { "name": "Japan", "code": "JP" },
    { "name": "Jersey", "code": "JE" },
    { "name": "Jordan", "code": "JO" },
    { "name": "Kazakhstan", "code": "KZ" },
    { "name": "Kenya", "code": "KE" },
    { "name": "Kiribati", "code": "KI" },
    { "name": 'Korea, Democratic People"S Republic of', "code": "KP" },
    { "name": "Korea, Republic of", "code": "KR" },
    { "name": "Kuwait", "code": "KW" },
    { "name": "Kyrgyzstan", "code": "KG" },
    { "name": 'Lao People"S Democratic Republic', "code": "LA" },
    { "name": "Latvia", "code": "LV" },
    { "name": "Lebanon", "code": "LB" },
    { "name": "Lesotho", "code": "LS" },
    { "name": "Liberia", "code": "LR" },
    { "name": "Libyan Arab Jamahiriya", "code": "LY" },
    { "name": "Liechtenstein", "code": "LI" },
    { "name": "Lithuania", "code": "LT" },
    { "name": "Luxembourg", "code": "LU" },
    { "name": "Macao", "code": "MO" },
    { "name": "Macedonia, The Former Yugoslav Republic of", "code": "MK" },
    { "name": "Madagascar", "code": "MG" },
    { "name": "Malawi", "code": "MW" },
    { "name": "Malaysia", "code": "MY" },
    { "name": "Maldives", "code": "MV" },
    { "name": "Mali", "code": "ML" },
    { "name": "Malta", "code": "MT" },
    { "name": "Marshall Islands", "code": "MH" },
    { "name": "Martinique", "code": "MQ" },
    { "name": "Mauritania", "code": "MR" },
    { "name": "Mauritius", "code": "MU" },
    { "name": "Mayotte", "code": "YT" },
    { "name": "Mexico", "code": "MX" },
    { "name": "Micronesia, Federated States of", "code": "FM" },
    { "name": "Moldova, Republic of", "code": "MD" },
    { "name": "Monaco", "code": "MC" },
    { "name": "Mongolia", "code": "MN" },
    { "name": "Montenegro", "code": "ME" },
    { "name": "Montserrat", "code": "MS" },
    { "name": "Morocco", "code": "MA" },
    { "name": "Mozambique", "code": "MZ" },
    { "name": "Myanmar", "code": "MM" },
    { "name": "Namibia", "code": "NA" },
    { "name": "Nauru", "code": "NR" },
    { "name": "Nepal", "code": "NP" },
    { "name": "Netherlands", "code": "NL" },
    { "name": "Netherlands Antilles", "code": "AN" },
    { "name": "New Caledonia", "code": "NC" },
    { "name": "New Zealand", "code": "NZ" },
    { "name": "Nicaragua", "code": "NI" },
    { "name": "Niger", "code": "NE" },
    { "name": "Nigeria", "code": "NG" },
    { "name": "Niue", "code": "NU" },
    { "name": "Norfolk Island", "code": "NF" },
    { "name": "Northern Mariana Islands", "code": "MP" },
    { "name": "Norway", "code": "NO" },
    { "name": "Oman", "code": "OM" },
    { "name": "Pakistan", "code": "PK" },
    { "name": "Palau", "code": "PW" },
    { "name": "Palestinian Territory, Occupied", "code": "PS" },
    { "name": "Panama", "code": "PA" },
    { "name": "Papua New Guinea", "code": "PG" },
    { "name": "Paraguay", "code": "PY" },
    { "name": "Peru", "code": "PE" },
    { "name": "Philippines", "code": "PH" },
    { "name": "Pitcairn", "code": "PN" },
    { "name": "Poland", "code": "PL" },
    { "name": "Portugal", "code": "PT" },
    { "name": "Puerto Rico", "code": "PR" },
    { "name": "Qatar", "code": "QA" },
    { "name": "Reunion", "code": "RE" },
    { "name": "Romania", "code": "RO" },
    { "name": "Russian Federation", "code": "RU" },
    { "name": "RWANDA", "code": "RW" },
    { "name": "Saint Helena", "code": "SH" },
    { "name": "Saint Kitts and Nevis", "code": "KN" },
    { "name": "Saint Lucia", "code": "LC" },
    { "name": "Saint Pierre and Miquelon", "code": "PM" },
    { "name": "Saint Vincent and the Grenadines", "code": "VC" },
    { "name": "Samoa", "code": "WS" },
    { "name": "San Marino", "code": "SM" },
    { "name": "Sao Tome and Principe", "code": "ST" },
    { "name": "Saudi Arabia", "code": "SA" },
    { "name": "Senegal", "code": "SN" },
    { "name": "Serbia", "code": "RS" },
    { "name": "Seychelles", "code": "SC" },
    { "name": "Sierra Leone", "code": "SL" },
    { "name": "Singapore", "code": "SG" },
    { "name": "Slovakia", "code": "SK" },
    { "name": "Slovenia", "code": "SI" },
    { "name": "Solomon Islands", "code": "SB" },
    { "name": "Somalia", "code": "SO" },
    { "name": "South Africa", "code": "ZA" },
    { "name": "South Georgia and the South Sandwich Islands", "code": "GS" },
    { "name": "Spain", "code": "ES" },
    { "name": "Sri Lanka", "code": "LK" },
    { "name": "Sudan", "code": "SD" },
    { "name": "Suriname", "code": "SR" },
    { "name": "Svalbard and Jan Mayen", "code": "SJ" },
    { "name": "Swaziland", "code": "SZ" },
    { "name": "Sweden", "code": "SE" },
    { "name": "Switzerland", "code": "CH" },
    { "name": "Syrian Arab Republic", "code": "SY" },
    { "name": "Taiwan, Province of China", "code": "TW" },
    { "name": "Tajikistan", "code": "TJ" },
    { "name": "Tanzania, United Republic of", "code": "TZ" },
    { "name": "Thailand", "code": "TH" },
    { "name": "Timor-Leste", "code": "TL" },
    { "name": "Togo", "code": "TG" },
    { "name": "Tokelau", "code": "TK" },
    { "name": "Tonga", "code": "TO" },
    { "name": "Trinidad and Tobago", "code": "TT" },
    { "name": "Tunisia", "code": "TN" },
    { "name": "Turkey", "code": "TR" },
    { "name": "Turkmenistan", "code": "TM" },
    { "name": "Turks and Caicos Islands", "code": "TC" },
    { "name": "Tuvalu", "code": "TV" },
    { "name": "Uganda", "code": "UG" },
    { "name": "Ukraine", "code": "UA" },
    { "name": "United Arab Emirates", "code": "AE" },
    { "name": "United Kingdom", "code": "GB" },
    { "name": "United States", "code": "US" },
    { "name": "United States Minor Outlying Islands", "code": "UM" },
    { "name": "Uruguay", "code": "UY" },
    { "name": "Uzbekistan", "code": "UZ" },
    { "name": "Vanuatu", "code": "VU" },
    { "name": "Venezuela", "code": "VE" },
    { "name": "Viet Nam", "code": "VN" },
    { "name": "Virgin Islands, British", "code": "VG" },
    { "name": "Virgin Islands, U.S.", "code": "VI" },
    { "name": "Wallis and Futuna", "code": "WF" },
    { "name": "Western Sahara", "code": "EH" },
    { "name": "Yemen", "code": "YE" },
    { "name": "Zambia", "code": "ZM" },
    { "name": "Zimbabwe", "code": "ZW" }
]